routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::get('/', 'PublicController@index');

Route::get('confirm-email/{code}/{uid}','PublicController@confirmEmail');

Route::get('privacy-policy','PublicController@privacyPolicy');
Route::get('terms','PublicController@terms');


Auth::routes();

Route::get('home',function(){return redirect('/dashboard');});
Route::get('/dashboard', 'UserController@index')->name('dashboard');

//admin role
Route::get('admin/dashboard','AdminController@dashboard');

Route::get('users','AdminController@users');
Route::get('users/banned','AdminController@bannedUsers');
Route::get('user/{uid}','AdminController@userDetails');
Route::get('user/{uid}/edit','AdminController@editUser');
Route::get('user/{uid}/ban','AdminController@banUser');
Route::get('user/{uid}/unban','AdminController@unbanUser');


Route::get('tasks','AdminController@tasks')->name('tasks.show');
Route::get('task/{task}','AdminController@taskDetails')->name('tasks.details');
Route::get('task/{task}/delete','AdminController@deleteTask')->name('tasks.destroy');
Route::get('tasks/pending','AdminController@pendingVideos')->name('tasks.pending');
Route::get('task/{task}/approve','AdminController@approveVideo')->name('tasks.approve');
Route::get('task/{task}/reject','AdminController@rejectVideo')->name('tasks.reject');


Route::get('cashouts','AdminController@cashouts')->name('cashouts.show');
Route::get('cashout/{cashout}/approve','AdminController@approveCashout')->name('cashouts.approve');
Route::get('cashout/{cashout}/reject','AdminController@rejectCashout')->name('cashouts.reject');


Route::get('deposits','AdminController@deposits')->name('deposits.show');

Route::get('summary','AdminController@summary')->name('summary.show');

Route::get('settings','AdminController@settings');
Route::get('settings/add','AdminController@addSetting');
Route::post('settings/add','AdminController@postAddSetting');
Route::get('settings/resend-unverified-emails','AdminController@resendUnverifiedEmails')->name('settings.resendUnverifiedEmails');


Route::get('task/add','UserController@addTask');

Route::get('task/{tid}/suspend','UserController@suspendTask');
Route::get('task/{tid}/resume','UserController@resumeTask');


Route::post('task/add','UserController@postAddTask');


//funding
Route::get('fund-account','AdminController@fundAccount')->name('funds.create');
Route::post('fund-account','AdminController@postFundAccount')->name('funds.store');

Route::get('logout','HomeController@logout');

app/task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class task extends Model
{
    protected $primaryKey = 'tid';
    protected $table = 'tasks';

	public function getExpiryAttribute( $value ) {
		return Carbon::createFromFormat("Y-m-d H:i:s",$value);
    }

	public function User() {
		return $this->belongsTo(User::class,'uid','uid');
    }

	public function Media() {
		return $this->hasMany(taskMedia::class,'tid','tid');
    }

	public function TaskUsers() {
		return $this->hasMany(taskUser::class,'tid','tid');
    }

	public function Users() {
		return $this->belongsToMany(User::class,'task_users','tuid','uid','tid');
    }


}

resources/views/tasks/details.blade.php
@extends('layouts.app')

@section('content')

    <style>
        label{
            font-weight: 800;
        }

        .postImagePreview img{
            width:100%;
            max-height:200px;
        }
    </style>
    <!-- Main Page Main Content-->
    <div class="main-content" id="main-content">

        @include('navs.top')
        <div class="content-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container-text">
                            <div class="welcome">

                                <div class="welcome-details">
                                    <div class="welcome-name">{{$task->name}}</div>
                                    <div class="welcome-role">Type -

                                        @if($task->type == 'videov2e')
                                            <span class="badge badge-info">View to Earn</span>
                                        @elseif($task->type == 'videop2v')
                                            <span class="badge badge-info">Pay to View</span>
                                            @else
                                            <span class="badge badge-info">{{$task->type}}</span>
                                        @endif

                                    </div>
                                </div>
                            </div>
                            <div class="all-tasks-section">
                                <div class="container-fluid row">


                                    <!-- left section -->

                                     @if(strtolower($task->type) == 'community')
                                        <div class="col-md-6 row">

                                        <label>Images </label><br>
                                            @foreach($task->Media as $media)
                                                <div class="col">
                                                    <img src="{{$media->url}}" width="100%">
                                                </div>
                                            @endforeach
                                        </div>
                                    @endif

                                    @if(strtolower($task->type) == 'videop2v' || strtolower($task->type) == 'videov2e')
                                         <div class="col-md-6">

                                         @foreach($task->Media as $media)
                                            <div class="col">
                                                <video style="width: 100%" controls controlsList="nodownload"  webkit-playsinline="webkit-playsinline"  poster="{{$media->thumbnail}}"  playsinline looped preload="auto">
                                                    <source src="{{$media->url}}" type="video/mp4">
                                                </video>

                                            </div>
                                        @endforeach

                                             <div align="center">
                                                 @if($task->isSuspended == 1)
                                                     <a class="btn btn-success" style="background-color: #7EDB8F;border: none; margin-right: 20px;" href="{{route('tasks.approve',['task' => $task->tid])}}">
                                                         Approve
                                                     </a>

                                                     <a class="btn btn-danger" style="background-color: darkred;border: none" href="{{route('tasks.reject',['task' => $task->tid])}}">
                                                         Reject
                                                     </a>
                                                 @endif
                                             </div>
                                         </div>
                                    @endif

                                    <!-- end left section -->


                                    <div class="col-md-6">

                                        <div class="form-group col-md-12">
                                            <label>USERNAME </label>

                                            <p>{{$task->User->username}}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>Name </label>

                                            <p>{{$task->User->name}}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>Phone </label>

                                            <p>{{$task->User->phone}}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>Email </label>
                                            <p>{{$task->User->email}}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>DESCRIPTION </label>

                                            <p>{{$task->longDescription}}</p>
                                        </div>


                                        <div class="form-group col-md-4">
                                            <label>Points </label>
                                            <p>{{ $task->points }}</p>

                                        </div>




                                        <div class="form-group col-md-12">
                                            <label>EXPIRATION DATE</label>
                                            <p>{{ $task->expiry }}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>MAX NO OF USERS </label>

                                            <p>{{ $task->maxUsers }}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>DURATION OF VERIFICATION</label>
                                            <p>{{ $task->verificationDuration }}</p>
                                        </div>

                                        <div class="form-group col-md-12">
                                            <label>Created</label>
                                            <p>
                                                {{$task->expiry->toDayDateTimeString()}}
                                                ({{$task->expiry->diffForHumans()}})
                                            </p>
                                        </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <!-- End of Page Main Content-->





@endsection

resources/views/tasks/manage.blade.php
<?php use Carbon\Carbon; use Illuminate\Support\Facades\Input; ?>
@extends('layouts.app')

@section('content')

    <style>
        label{
            font-weight: 800;
        }
    </style>
    <!-- Main Page Main Content-->
    <div class="main-content" id="main-content">

        @include('navs.top')
        <div class="content-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container-text">
                            <div class="welcome">
                                <div class="welcome-image">
                                    <img src="img/user.png">
                                </div>
                                @if(Input::has('status'))
                                    <div class="welcome-details">
                                        <div class="welcome-name">{{Input::get('status')}} Tasks</div>
                                        <div class="welcome-role">LIST OF ALL TASKS {{strtoupper(Input::get('status'))}}</div>
                                    </div>
                                @else
                                    <div class="welcome-details">
                                        <div class="welcome-name">View Tasks</div>
                                        <div class="welcome-role">LIST OF ALL TASKS</div>
                                    </div>
                                @endif
                            </div>
                            <div class="all-tasks-section">
                                <div class="container-fluid">

                                    <div class="col-lg-12 col-md-12 col-sm-12 all-tasks">
                                        All tasks
                                        <form style="float: right;">
                                            <input type="hidden" name="type" value="{{request()->input('type')}}">
                                            <input type="text" name="search" value="{{Input::get('search')}}" placeholder="Search">
                                        </form>
                                        <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Created Task</th>
                                                    <th scope="col">Created By (username)</th>
                                                    <th scope="col">Type</th>
                                                    <th scope="col">Task Status</th>
                                                    <th scope="col">Expiry</th>
                                                    <th scope="col">No Of Users</th>
                                                    <th scope="col"></th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                @if(count($tasks) <= 0 )
                                                    <tr>
                                                        <td align="center" colspan="8">
                                                            No tasks
                                                        </td>
                                                    </tr>
                                                @endif
                                                @foreach($tasks as $task)
                                                    <tr>
                                                        <td>{{$task->created_at->diffForHumans()}}</td>
                                                        <td>
                                                            {{$task->name}}
                                                        </td>
                                                        <td>
                                                            {{$task->User->username}}
                                                        </td>
                                                        <td>
                                                            {{$task->type}}
                                                        </td>
                                                        @if($task->status == 'Completed')
                                                            <td class="completed-task">Completed</td>
                                                        @endif
                                                        @if($task->status == 'In Progress')
                                                            <td class="in-progress-task">In Progress</td>
                                                        @endif
                                                        @if($task->status == 'Cancelled')
                                                            <td class="cancelled-task">Cancelled</td>
                                                        @endif
                                                        <td>
                                                            {{Carbon::createFromFormat("Y-m-d H:i:s",$task->expiry)->diffForHumans()}}
                                                        </td>
                                                        <td>
                                                            {{$task->maxUsers}}
                                                        </td>

                                                        <td>
                                                            <a class="badge badge-success" style="background-color: #7EDB8F;" href="{{url('task/' . $task->tid)}}">
                                                                View
                                                            </a>

                                                            <a class="badge badge-danger" href="{{route('tasks.destroy',$task->tid)}}">
                                                                Delete
                                                            </a>

                                                        </td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>

                                            {{$tasks->appends(request()->input())->links()}}
                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Page Main Content-->

    <script>
        $(document).ready( function() {

            $('#expiry').datetimepicker();
            // $('#endTime').datetimepicker({
            //     // numberOfMonths: 2,
            //     // showButtonPanel: true
            // });

        } );
    </script>



@endsection

resources/views/tasks/pending.blade.php
<?php use Carbon\Carbon; use Illuminate\Support\Facades\Input; ?>
@extends('layouts.app')

@section('content')

    <style>
        label{
            font-weight: 800;
        }
    </style>
    <!-- Main Page Main Content-->
    <div class="main-content" id="main-content">

        @include('navs.top')
        <div class="content-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container-text">
                            <div class="welcome">
                                {{--<div class="welcome-image">--}}
                                    {{--<img src="img/user.png">--}}
                                {{--</div>--}}
                                @if(Input::has('status'))
                                    <div class="welcome-details">
                                        <div class="welcome-name">{{Input::get('status')}} Tasks</div>
                                        <div class="welcome-role">LIST OF ALL TASKS {{strtoupper(Input::get('status'))}}</div>
                                    </div>
                                @else
                                    <div class="welcome-details">
                                        <div class="welcome-name">View Tasks</div>
                                        <div class="welcome-role">LIST OF ALL TASKS</div>
                                    </div>
                                @endif
                            </div>
                            <div class="all-tasks-section">
                                <div class="container-fluid">

                                    <div class="col-lg-12 col-md-12 col-sm-12 all-tasks">
                                        All tasks
                                        <form style="float: right;">
                                            <input type="hidden" name="type" value="{{request()->input('type')}}">
                                            <input type="text" name="search" value="{{Input::get('search')}}" placeholder="Search">
                                        </form>
                                        <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Created Task</th>
                                                    <th scope="col">Created By (username)</th>
                                                    <th scope="col">Type</th>
                                                    <th scope="col">Task Status</th>
                                                    <th scope="col">Expiry</th>
                                                    <th scope="col">No Of Users</th>
                                                    <th scope="col"></th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                @if(count($tasks) <= 0 )
                                                    <tr>
                                                        <td align="center" colspan="8">
                                                            No tasks
                                                        </td>
                                                    </tr>
                                                @endif
                                                @foreach($tasks as $task)
                                                    <tr>
                                                        <td>{{$task->created_at->diffForHumans()}}</td>
                                                        <td>
                                                            {{$task->name}}
                                                        </td>
                                                        <td>
                                                            {{$task->User->username}}
                                                        </td>
                                                        <td>
                                                            {{$task->type}}
                                                        </td>
                                                        @if($task->status == 'Completed')
                                                            <td class="completed-task">Completed</td>
                                                        @endif
                                                        @if($task->status == 'In Progress')
                                                            <td class="in-progress-task">In Progress</td>
                                                        @endif
                                                        @if($task->status == 'Cancelled')
                                                            <td class="cancelled-task">Cancelled</td>
                                                        @endif
                                                        <td>
                                                            {{Carbon::createFromFormat("Y-m-d H:i:s",$task->expiry)->diffForHumans()}}
                                                        </td>
                                                        <td>
                                                            {{$task->maxUsers}}
                                                        </td>

                                                        <td>
                                                            <a class="badge badge-success" style="background-color: #7EDB8F;" href="{{url('task/' . $task->tid)}}">
                                                                View
                                                            </a>

                                                            <a class="badge badge-danger" href="{{route('tasks.destroy',$task->tid)}}">
                                                                Delete
                                                            </a>

                                                        </td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>

                                            {{$tasks->appends(request()->input())->links()}}
                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End of Page Main Content-->

    <script>
        $(document).ready( function() {

            $('#expiry').datetimepicker();
            // $('#endTime').datetimepicker({
            //     // numberOfMonths: 2,
            //     // showButtonPanel: true
            // });

        } );
    </script>



@endsection